Rebuild 10.0 (s390x)
AnacondaRecipes/humanfriendly-feedstock pull request #5
Opened 2022-11-08 19:55 UTC by ELundby45

2022-11-08 19:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_5fa1r1jwy4/clone/recipe/meta.yaml:41: invalid_url: https://humanfriendly.readthedocs.org : URL domain redirect humanfriendly.readthedocs.org ->  humanfriendly.readthedocs.io
WARNING: /tmp/abs_5fa1r1jwy4/clone/recipe/meta.yaml:50: missing_license_url: The recipe is missing a license_url
Errors were found

</details>

2022-11-08 23:45 UTC, AndrewVallette approved these changes
LGTM!

2022-11-09 06:31 UTC, katietz requested changes

2022-11-09 06:31 UTC, katietz commented on recipe/meta.yaml
> +  doc_source_url: https://github.com/xolox/python-humanfriendly/tree/master/docs
there is a doc_url, please don't add superflous doc_source_url

2022-11-09 06:31 UTC, katietz commented on recipe/meta.yaml
> +  license_url: https://github.com/xolox/python-humanfriendly/blob/master/LICENSE.txt
the license file is in the package. no need (even dangerous in terms of correctness) to add here this superflous license_url on top. please stop this habbit

2022-11-09 17:51 UTC, varlackc approved these changes
LGTM

2022-11-09 17:52 UTC, merged